name 'jhoblitt-smartd'
version '2.2.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'MIT'
project_page 'https://github.com/jhoblitt/puppet-smartd'
source 'https://github.com/jhoblitt/puppet-smartd'
summary 'Manages the smartmontools package including the smartd daemon'
description 'Manages the smartmontools package including the smartd daemon'
dependency 'csail/shell_config', '>= 0.0.1'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
